OSM_BASE_URL = 'https://api.openstreetmap.org/'
OSM_TOKEN = 'SlEvGh8muTajOfr35mBkkTTQ26dsVNuVShD4efzcArM'
USER = 'osm_worker111'
PASSWORD = 'tq5h2kb0'
MAP_URL = 'https://www.openstreetmap.org/export/embed.html?bbox='